- name: Install restic
  apt:
    name: restic
    state: present
  become: yes

- name: Get path to restic binary
  command: which restic
  register: which_restic

- set_fact:
    restic_binary: "{{ which_restic.stdout }}"

- name: Create restic config dir
  file:
    path: "{{ restic_config_dir }}"
    state: directory
  become: yes

- name: Generate restic config file
  template:
    src: restic_env.j2
    dest: "{{ restic_config }}"
  become: yes

- name: Initialize the restic repository
  shell:
    cmd: ". {{ restic_config }}; {{ restic_binary }} init; sudo touch {{ restic_config_dir }}/repo_initiated"
    creates: "{{ restic_config_dir }}/repo_initiated"

- name: Install cron tab, so restic creates backups for the wiki
  cron:
    name: Backup {{ tiddlywiki_wiki_name }}
    minute: "42"
    job: "source {{ restic_config }}; {{ restic_binary }} backup -q {{ tiddlywiki_data_dir }}; {{ restic_binary }} forget -q --prune --keep-hourly 24 --keep-daily 7"
    state: present
  become: yes