- name: Install restic
  apt:
    name: restic
    state: present
  become: yes

- name: Get path to restic binary
  command: which restic
  register: which_restic

- set_fact:
    restic_binary: "{{ which_restic.stdout }}"

- name: Create restic repo config dir
  file:
    path: "{{ restic_repo_config_dir }}"
    state: directory
  become: yes

- name: Generate restic config file
  template:
    src: restic_env.j2
    dest: "{{ restic_repo_config }}"
  become: yes

- name: Initialize the restic repository
  shell:
    cmd: ". {{ restic_repo_config }}; {{ restic_binary }} init; sudo touch {{ restic_repo_config_dir }}/repo_initiated"
    creates: "{{ restic_repo_config_dir }}/repo_initiated"

- name: Install cron tab, so restic creates backups for the wiki
  cron:
    name: Backup {{ restic_repo_name }}
    minute: "42"
    job: ". {{ restic_repo_config }}; {{ restic_binary }} backup -q {{ restic_dir_to_backup }}; {{ restic_binary }} forget -q --prune --keep-hourly 24 --keep-daily 7"
    state: present
  become: yes